name: Build, Test, Version, and Deploy Uptime Kuma (Develop)

on:
  push:
    branches:
      - develop  # Trigger de actie op een push naar de develop branch
  pull_request:
    branches:
      - develop  # Trigger de actie op een pull request naar de develop 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Install Dependencies
        run: |
          npm install
      - name: Run Build
        run: |
          npm run build

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Install Playwright and Dependencies
        run: |
          npm install playwright
          npx playwright install  # Installeer de browser afhankelijkheden
      - name: Run Tests
        run: |
          if [ "$SKIP_MQTT_TESTS" = "true" ]; then
            echo "Skipping MQTT tests" && npm run test-backend;
          else
            npm run test-backend || echo "Ignoring backend test error"
            npm run test-e2e || echo "Ignoring Playwright test error"
          fi

  version:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Install Standard Version
        run: |
          npm install --save-dev standard-version
      - name: Bump Version and Create Tag
        run: |
          npm run release
      - name: Push Changes and Tags
        run: |
          git push --follow-tags

  deploy:
    runs-on: ubuntu-latest
    needs: [build, test, version]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      # Stop en verwijder de bestaande container, indien aanwezig
      - name: Stop and Remove Existing Containers
        run: |
          docker ps -a | grep 'uptime-kuma' | awk '{print $1}' | xargs -I {} docker rm -f {}

      # Pull de laatste wijzigingen uit Git
      - name: Pull Latest Git Changes
        run: |
          git fetch --all
          git reset --hard origin/develop

      # Start de nieuwe container met de laatste code
      - name: Deploy with Latest Code
        run: |
          docker run -d --restart=always -p 3001:3001 -v uptime-kuma:/app/data --name uptime-kuma louislam/uptime-kuma:1
