---
- name: Install Docker
  hosts: localhost
  become: yes
  connection: local
  tasks:
  - name: Update Ubuntu
    apt:
      update_cache: yes

  - name: Install apt-transport-https, ca-certificates, curl, and software-properties-common
    apt:
      name:
        - apt-transport-https
        - ca-certificates
        - curl
        - software-properties-common
      state: present

  - name: Add the GPG key for the official Docker repository
    shell: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg

  - name: Add the Docker repository to APT sources
    shell: echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

  - name: Update Ubuntu
    apt:
      update_cache: yes

  - name: Check Docker repo instead of the default Ubuntu repo
    shell: apt-cache policy docker-ce

  - name: Install Docker
    apt:
      name: docker-ce
      state: present

  - name: Add the current user to the docker group
    user:
      name: "{{ ansible_user_id }}"
      groups: docker
      append: yes

  - name: Notify user to log out and log back in
    debug:
      msg: "Docker installation complete. Please log out and log back in for Docker group changes to take effect."

  - name: Download the official Ubuntu Docker image
    shell: docker pull ubuntu
    become: false
