---
- name: Install and configure Zabbix agent on client
  hosts: localhost
  become: yes
  connection: local
  vars:
    zabbix_server_ip: "{{ zabbix_server_ip }}"  
    client_ip: "{{ ansible_default_ipv4.address }}" 

  tasks:
    - name: Download Zabbix repository package
      get_url:
        url: "https://repo.zabbix.com/zabbix/7.0/ubuntu/pool/main/z/zabbix-release/zabbix-release_7.0-2+ubuntu24.04_all.deb"
        dest: "/tmp/zabbix-release_7.0-2+ubuntu24.04_all.deb"

    - name: Install Zabbix repository
      apt:
        deb: "/tmp/zabbix-release_7.0-2+ubuntu24.04_all.deb"

    - name: Update the system
      apt:
        update_cache: yes

    - name: Install Zabbix agent
      apt:
        name: zabbix-agent
        state: present

    - name: Configure Zabbix agent
      lineinfile:
        path: /etc/zabbix/zabbix_agentd.conf
        regexp: '^Server='
        line: "Server={{ zabbix_server_ip }}"

    - name: Configure Zabbix agent to allow server to connect
      lineinfile:
        path: /etc/zabbix/zabbix_agentd.conf
        regexp: '^ServerActive='
        line: "ServerActive={{ zabbix_server_ip }}"

    - name: Configure Zabbix agent with client IP
      lineinfile:
        path: /etc/zabbix/zabbix_agentd.conf
        regexp: '^Hostname='
        line: "Hostname={{ client_ip }}"

    - name: Configure Zabbix agent HostMetadata
      lineinfile:
        path: /etc/zabbix/zabbix_agentd.conf
        regexp: '^# HostMetadata='
        line: "HostMetadata={{ host_metadata }}"

    - name: Restart Zabbix agent
      systemd:
        name: zabbix-agent
        state: restarted

    - name: Enable Zabbix agent to start on boot
      systemd:
        name: zabbix-agent
        enabled: yes
